version: "3.8"

services:
  latextrans-ui:
    build:
      context: .           # where your Dockerfile is
      dockerfile: Dockerfile
    image: latextrans-ui   # optional name for the built image
    container_name: latextrans-ui
    ports:
      - "8501:8501"
    environment:
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      # OPENAI_API_KEY: ${OPENAI_API_KEY}   # optional default
    restart: unless-stopped
